//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestServiceConsole.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sent", Namespace="http://schemas.datacontract.org/2004/07/WCFSocmedProcessing.Model")]
    [System.SerializableAttribute()]
    public partial class Sent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyCompositeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyHtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyTextPlainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsAttachmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsScheduledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Sent_Attachment[] Sent_AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Sent_Facebook Sent_FacebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyComposite {
            get {
                return this.BodyCompositeField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyCompositeField, value) != true)) {
                    this.BodyCompositeField = value;
                    this.RaisePropertyChanged("BodyComposite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyHtml {
            get {
                return this.BodyHtmlField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyHtmlField, value) != true)) {
                    this.BodyHtmlField = value;
                    this.RaisePropertyChanged("BodyHtml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyTextPlain {
            get {
                return this.BodyTextPlainField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyTextPlainField, value) != true)) {
                    this.BodyTextPlainField = value;
                    this.RaisePropertyChanged("BodyTextPlain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcAddress {
            get {
                return this.CcAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CcAddressField, value) != true)) {
                    this.CcAddressField = value;
                    this.RaisePropertyChanged("CcAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcName {
            get {
                return this.CcNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CcNameField, value) != true)) {
                    this.CcNameField = value;
                    this.RaisePropertyChanged("CcName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAddress {
            get {
                return this.FromAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAddressField, value) != true)) {
                    this.FromAddressField = value;
                    this.RaisePropertyChanged("FromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromName {
            get {
                return this.FromNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FromNameField, value) != true)) {
                    this.FromNameField = value;
                    this.RaisePropertyChanged("FromName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsAttachment {
            get {
                return this.IsAttachmentField;
            }
            set {
                if ((this.IsAttachmentField.Equals(value) != true)) {
                    this.IsAttachmentField = value;
                    this.RaisePropertyChanged("IsAttachment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsScheduled {
            get {
                return this.IsScheduledField;
            }
            set {
                if ((this.IsScheduledField.Equals(value) != true)) {
                    this.IsScheduledField = value;
                    this.RaisePropertyChanged("IsScheduled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SentDate {
            get {
                return this.SentDateField;
            }
            set {
                if ((this.SentDateField.Equals(value) != true)) {
                    this.SentDateField = value;
                    this.RaisePropertyChanged("SentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Sent_Attachment[] Sent_Attachments {
            get {
                return this.Sent_AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.Sent_AttachmentsField, value) != true)) {
                    this.Sent_AttachmentsField = value;
                    this.RaisePropertyChanged("Sent_Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Sent_Facebook Sent_Facebook {
            get {
                return this.Sent_FacebookField;
            }
            set {
                if ((object.ReferenceEquals(this.Sent_FacebookField, value) != true)) {
                    this.Sent_FacebookField = value;
                    this.RaisePropertyChanged("Sent_Facebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToAddress {
            get {
                return this.ToAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ToAddressField, value) != true)) {
                    this.ToAddressField = value;
                    this.RaisePropertyChanged("ToAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToName {
            get {
                return this.ToNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ToNameField, value) != true)) {
                    this.ToNameField = value;
                    this.RaisePropertyChanged("ToName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sent_Facebook", Namespace="http://schemas.datacontract.org/2004/07/WCFSocmedProcessing.Model")]
    [System.SerializableAttribute()]
    public partial class Sent_Facebook : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Master_MessageType Master_MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Sent SentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToAddressFbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToNameFbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMessageType {
            get {
                return this.IdMessageTypeField;
            }
            set {
                if ((this.IdMessageTypeField.Equals(value) != true)) {
                    this.IdMessageTypeField = value;
                    this.RaisePropertyChanged("IdMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Master_MessageType Master_MessageType {
            get {
                return this.Master_MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Master_MessageTypeField, value) != true)) {
                    this.Master_MessageTypeField = value;
                    this.RaisePropertyChanged("Master_MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Sent Sent {
            get {
                return this.SentField;
            }
            set {
                if ((object.ReferenceEquals(this.SentField, value) != true)) {
                    this.SentField = value;
                    this.RaisePropertyChanged("Sent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToAddressFb {
            get {
                return this.ToAddressFbField;
            }
            set {
                if ((object.ReferenceEquals(this.ToAddressFbField, value) != true)) {
                    this.ToAddressFbField = value;
                    this.RaisePropertyChanged("ToAddressFb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToNameFb {
            get {
                return this.ToNameFbField;
            }
            set {
                if ((object.ReferenceEquals(this.ToNameFbField, value) != true)) {
                    this.ToNameFbField = value;
                    this.RaisePropertyChanged("ToNameFb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sent_Attachment", Namespace="http://schemas.datacontract.org/2004/07/WCFSocmedProcessing.Model")]
    [System.SerializableAttribute()]
    public partial class Sent_Attachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Binary FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Master_FileType Master_FileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Sent SentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Binary FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.FileSizeField, value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType {
            get {
                return this.FileTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FileTypeField, value) != true)) {
                    this.FileTypeField = value;
                    this.RaisePropertyChanged("FileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdSent {
            get {
                return this.IdSentField;
            }
            set {
                if ((this.IdSentField.Equals(value) != true)) {
                    this.IdSentField = value;
                    this.RaisePropertyChanged("IdSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Master_FileType Master_FileType {
            get {
                return this.Master_FileTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Master_FileTypeField, value) != true)) {
                    this.Master_FileTypeField = value;
                    this.RaisePropertyChanged("Master_FileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Sent Sent {
            get {
                return this.SentField;
            }
            set {
                if ((object.ReferenceEquals(this.SentField, value) != true)) {
                    this.SentField = value;
                    this.RaisePropertyChanged("Sent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    [System.SerializableAttribute()]
    public partial class Binary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Master_FileType", Namespace="http://schemas.datacontract.org/2004/07/WCFSocmedProcessing.Model")]
    [System.SerializableAttribute()]
    public partial class Master_FileType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Binary DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Sent_Attachment[] Sent_AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Binary Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Sent_Attachment[] Sent_Attachments {
            get {
                return this.Sent_AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.Sent_AttachmentsField, value) != true)) {
                    this.Sent_AttachmentsField = value;
                    this.RaisePropertyChanged("Sent_Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Master_MessageType", Namespace="http://schemas.datacontract.org/2004/07/WCFSocmedProcessing.Model")]
    [System.SerializableAttribute()]
    public partial class Master_MessageType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Inbox_Facebook[] Inbox_FacebooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Sent_Facebook[] Sent_FacebooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Inbox_Facebook[] Inbox_Facebooks {
            get {
                return this.Inbox_FacebooksField;
            }
            set {
                if ((object.ReferenceEquals(this.Inbox_FacebooksField, value) != true)) {
                    this.Inbox_FacebooksField = value;
                    this.RaisePropertyChanged("Inbox_Facebooks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Sent_Facebook[] Sent_Facebooks {
            get {
                return this.Sent_FacebooksField;
            }
            set {
                if ((object.ReferenceEquals(this.Sent_FacebooksField, value) != true)) {
                    this.Sent_FacebooksField = value;
                    this.RaisePropertyChanged("Sent_Facebooks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inbox_Facebook", Namespace="http://schemas.datacontract.org/2004/07/WCFSocmedProcessing.Model")]
    [System.SerializableAttribute()]
    public partial class Inbox_Facebook : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAddressFbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromNameFbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Inbox InboxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsAnalizedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Master_MessageType Master_MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAddressFb {
            get {
                return this.FromAddressFbField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAddressFbField, value) != true)) {
                    this.FromAddressFbField = value;
                    this.RaisePropertyChanged("FromAddressFb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromNameFb {
            get {
                return this.FromNameFbField;
            }
            set {
                if ((object.ReferenceEquals(this.FromNameFbField, value) != true)) {
                    this.FromNameFbField = value;
                    this.RaisePropertyChanged("FromNameFb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMessageType {
            get {
                return this.IdMessageTypeField;
            }
            set {
                if ((this.IdMessageTypeField.Equals(value) != true)) {
                    this.IdMessageTypeField = value;
                    this.RaisePropertyChanged("IdMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Inbox Inbox {
            get {
                return this.InboxField;
            }
            set {
                if ((object.ReferenceEquals(this.InboxField, value) != true)) {
                    this.InboxField = value;
                    this.RaisePropertyChanged("Inbox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsAnalized {
            get {
                return this.IsAnalizedField;
            }
            set {
                if ((this.IsAnalizedField.Equals(value) != true)) {
                    this.IsAnalizedField = value;
                    this.RaisePropertyChanged("IsAnalized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Master_MessageType Master_MessageType {
            get {
                return this.Master_MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Master_MessageTypeField, value) != true)) {
                    this.Master_MessageTypeField = value;
                    this.RaisePropertyChanged("Master_MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inbox", Namespace="http://schemas.datacontract.org/2004/07/WCFSocmedProcessing.Model")]
    [System.SerializableAttribute()]
    public partial class Inbox : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyCompositeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyHtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyTextPlainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceConsole.ServiceReference1.Inbox_Facebook Inbox_FacebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsAttachmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsFilteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReceivedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReplyToAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReplyToNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyComposite {
            get {
                return this.BodyCompositeField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyCompositeField, value) != true)) {
                    this.BodyCompositeField = value;
                    this.RaisePropertyChanged("BodyComposite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyHtml {
            get {
                return this.BodyHtmlField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyHtmlField, value) != true)) {
                    this.BodyHtmlField = value;
                    this.RaisePropertyChanged("BodyHtml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyTextPlain {
            get {
                return this.BodyTextPlainField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyTextPlainField, value) != true)) {
                    this.BodyTextPlainField = value;
                    this.RaisePropertyChanged("BodyTextPlain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcAddress {
            get {
                return this.CcAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CcAddressField, value) != true)) {
                    this.CcAddressField = value;
                    this.RaisePropertyChanged("CcAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcName {
            get {
                return this.CcNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CcNameField, value) != true)) {
                    this.CcNameField = value;
                    this.RaisePropertyChanged("CcName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAddress {
            get {
                return this.FromAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAddressField, value) != true)) {
                    this.FromAddressField = value;
                    this.RaisePropertyChanged("FromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromName {
            get {
                return this.FromNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FromNameField, value) != true)) {
                    this.FromNameField = value;
                    this.RaisePropertyChanged("FromName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceConsole.ServiceReference1.Inbox_Facebook Inbox_Facebook {
            get {
                return this.Inbox_FacebookField;
            }
            set {
                if ((object.ReferenceEquals(this.Inbox_FacebookField, value) != true)) {
                    this.Inbox_FacebookField = value;
                    this.RaisePropertyChanged("Inbox_Facebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsAttachment {
            get {
                return this.IsAttachmentField;
            }
            set {
                if ((this.IsAttachmentField.Equals(value) != true)) {
                    this.IsAttachmentField = value;
                    this.RaisePropertyChanged("IsAttachment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsFiltered {
            get {
                return this.IsFilteredField;
            }
            set {
                if ((this.IsFilteredField.Equals(value) != true)) {
                    this.IsFilteredField = value;
                    this.RaisePropertyChanged("IsFiltered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReceivedDate {
            get {
                return this.ReceivedDateField;
            }
            set {
                if ((this.ReceivedDateField.Equals(value) != true)) {
                    this.ReceivedDateField = value;
                    this.RaisePropertyChanged("ReceivedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReplyToAddress {
            get {
                return this.ReplyToAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ReplyToAddressField, value) != true)) {
                    this.ReplyToAddressField = value;
                    this.RaisePropertyChanged("ReplyToAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReplyToName {
            get {
                return this.ReplyToNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReplyToNameField, value) != true)) {
                    this.ReplyToNameField = value;
                    this.RaisePropertyChanged("ReplyToName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToAddress {
            get {
                return this.ToAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ToAddressField, value) != true)) {
                    this.ToAddressField = value;
                    this.RaisePropertyChanged("ToAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToName {
            get {
                return this.ToNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ToNameField, value) != true)) {
                    this.ToNameField = value;
                    this.RaisePropertyChanged("ToName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_ScheduleDetail", Namespace="http://schemas.datacontract.org/2004/07/WCFSocmedProcessing.Model")]
    [System.SerializableAttribute()]
    public partial class View_ScheduleDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> ExecuteTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunctionToCallNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFunctionToCallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMSchedulerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsMScheduleActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsScheduleDetailActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSchedulerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> ExecuteTime {
            get {
                return this.ExecuteTimeField;
            }
            set {
                if ((this.ExecuteTimeField.Equals(value) != true)) {
                    this.ExecuteTimeField = value;
                    this.RaisePropertyChanged("ExecuteTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunctionToCallName {
            get {
                return this.FunctionToCallNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionToCallNameField, value) != true)) {
                    this.FunctionToCallNameField = value;
                    this.RaisePropertyChanged("FunctionToCallName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFunctionToCall {
            get {
                return this.IdFunctionToCallField;
            }
            set {
                if ((this.IdFunctionToCallField.Equals(value) != true)) {
                    this.IdFunctionToCallField = value;
                    this.RaisePropertyChanged("IdFunctionToCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMScheduler {
            get {
                return this.IdMSchedulerField;
            }
            set {
                if ((this.IdMSchedulerField.Equals(value) != true)) {
                    this.IdMSchedulerField = value;
                    this.RaisePropertyChanged("IdMScheduler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsMScheduleActive {
            get {
                return this.IsMScheduleActiveField;
            }
            set {
                if ((this.IsMScheduleActiveField.Equals(value) != true)) {
                    this.IsMScheduleActiveField = value;
                    this.RaisePropertyChanged("IsMScheduleActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsParameter {
            get {
                return this.IsParameterField;
            }
            set {
                if ((this.IsParameterField.Equals(value) != true)) {
                    this.IsParameterField = value;
                    this.RaisePropertyChanged("IsParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsScheduleDetailActive {
            get {
                return this.IsScheduleDetailActiveField;
            }
            set {
                if ((this.IsScheduleDetailActiveField.Equals(value) != true)) {
                    this.IsScheduleDetailActiveField = value;
                    this.RaisePropertyChanged("IsScheduleDetailActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSchedulerName {
            get {
                return this.MSchedulerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MSchedulerNameField, value) != true)) {
                    this.MSchedulerNameField = value;
                    this.RaisePropertyChanged("MSchedulerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestWcfHelloWord", ReplyAction="http://tempuri.org/IService1/TestWcfHelloWordResponse")]
        string TestWcfHelloWord(out string messageInfo, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostImageStatusUpdate", ReplyAction="http://tempuri.org/IService1/PostImageStatusUpdateResponse")]
        void PostImageStatusUpdate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateDraftMail", ReplyAction="http://tempuri.org/IService1/CreateDraftMailResponse")]
        bool CreateDraftMail(out string messageInfo, string messageToSent);
        
        // CODEGEN: Generating message contract since the operation UploadImageStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadImageStatus", ReplyAction="http://tempuri.org/IService1/UploadImageStatusResponse")]
        TestServiceConsole.ServiceReference1.UploadImageStatusResponse UploadImageStatus(TestServiceConsole.ServiceReference1.DocInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RetrieveInboxMail", ReplyAction="http://tempuri.org/IService1/RetrieveInboxMailResponse")]
        bool RetrieveInboxMail(out string messageInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FilterInboxFacebook", ReplyAction="http://tempuri.org/IService1/FilterInboxFacebookResponse")]
        bool FilterInboxFacebook(out string messageInfo, System.Nullable<System.DateTime> date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AnalizeFacebookResponse", ReplyAction="http://tempuri.org/IService1/AnalizeFacebookResponseResponse")]
        bool AnalizeFacebookResponse(out TestServiceConsole.ServiceReference1.Sent[] draftSent, out TestServiceConsole.ServiceReference1.Sent_Facebook[] draftSentFacebook, out int[] idInboxList, out string messageInfo, System.Nullable<System.DateTime> date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SentDraftMail", ReplyAction="http://tempuri.org/IService1/SentDraftMailResponse")]
        bool SentDraftMail(out string messageInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveDraftMail", ReplyAction="http://tempuri.org/IService1/SaveDraftMailResponse")]
        bool SaveDraftMail(out string messageInfo, TestServiceConsole.ServiceReference1.Sent[] draftSent, TestServiceConsole.ServiceReference1.Sent_Facebook[] draftSentFacebook, int[] idInboxList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SmartReplyDraftCreation", ReplyAction="http://tempuri.org/IService1/SmartReplyDraftCreationResponse")]
        bool SmartReplyDraftCreation(out string messageInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SmartUpdateStatus", ReplyAction="http://tempuri.org/IService1/SmartUpdateStatusResponse")]
        bool SmartUpdateStatus(out string messageInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SentHappyBirthday", ReplyAction="http://tempuri.org/IService1/SentHappyBirthdayResponse")]
        bool SentHappyBirthday(out string messageInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SentWeatherInfoToday", ReplyAction="http://tempuri.org/IService1/SentWeatherInfoTodayResponse")]
        bool SentWeatherInfoToday(out string messageInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoadSchedule", ReplyAction="http://tempuri.org/IService1/LoadScheduleResponse")]
        bool LoadSchedule(out TestServiceConsole.ServiceReference1.View_ScheduleDetail[] listScheduler, out string messageInfo, System.DateTime dateNow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExecuteSchedule", ReplyAction="http://tempuri.org/IService1/ExecuteScheduleResponse")]
        bool ExecuteSchedule(out string messageInfo, string functionName);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public double FileSize;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileContent;
        
        public DocInfo() {
        }
        
        public DocInfo(string FileName, double FileSize, string Id, System.IO.Stream FileContent) {
            this.FileName = FileName;
            this.FileSize = FileSize;
            this.Id = Id;
            this.FileContent = FileContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadImageStatusResponse {
        
        public UploadImageStatusResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TestServiceConsole.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TestServiceConsole.ServiceReference1.IService1>, TestServiceConsole.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestWcfHelloWord(out string messageInfo, int value) {
            return base.Channel.TestWcfHelloWord(out messageInfo, value);
        }
        
        public void PostImageStatusUpdate() {
            base.Channel.PostImageStatusUpdate();
        }
        
        public bool CreateDraftMail(out string messageInfo, string messageToSent) {
            return base.Channel.CreateDraftMail(out messageInfo, messageToSent);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServiceConsole.ServiceReference1.UploadImageStatusResponse TestServiceConsole.ServiceReference1.IService1.UploadImageStatus(TestServiceConsole.ServiceReference1.DocInfo request) {
            return base.Channel.UploadImageStatus(request);
        }
        
        public void UploadImageStatus(string FileName, double FileSize, string Id, System.IO.Stream FileContent) {
            TestServiceConsole.ServiceReference1.DocInfo inValue = new TestServiceConsole.ServiceReference1.DocInfo();
            inValue.FileName = FileName;
            inValue.FileSize = FileSize;
            inValue.Id = Id;
            inValue.FileContent = FileContent;
            TestServiceConsole.ServiceReference1.UploadImageStatusResponse retVal = ((TestServiceConsole.ServiceReference1.IService1)(this)).UploadImageStatus(inValue);
        }
        
        public bool RetrieveInboxMail(out string messageInfo) {
            return base.Channel.RetrieveInboxMail(out messageInfo);
        }
        
        public bool FilterInboxFacebook(out string messageInfo, System.Nullable<System.DateTime> date) {
            return base.Channel.FilterInboxFacebook(out messageInfo, date);
        }
        
        public bool AnalizeFacebookResponse(out TestServiceConsole.ServiceReference1.Sent[] draftSent, out TestServiceConsole.ServiceReference1.Sent_Facebook[] draftSentFacebook, out int[] idInboxList, out string messageInfo, System.Nullable<System.DateTime> date) {
            return base.Channel.AnalizeFacebookResponse(out draftSent, out draftSentFacebook, out idInboxList, out messageInfo, date);
        }
        
        public bool SentDraftMail(out string messageInfo) {
            return base.Channel.SentDraftMail(out messageInfo);
        }
        
        public bool SaveDraftMail(out string messageInfo, TestServiceConsole.ServiceReference1.Sent[] draftSent, TestServiceConsole.ServiceReference1.Sent_Facebook[] draftSentFacebook, int[] idInboxList) {
            return base.Channel.SaveDraftMail(out messageInfo, draftSent, draftSentFacebook, idInboxList);
        }
        
        public bool SmartReplyDraftCreation(out string messageInfo) {
            return base.Channel.SmartReplyDraftCreation(out messageInfo);
        }
        
        public bool SmartUpdateStatus(out string messageInfo) {
            return base.Channel.SmartUpdateStatus(out messageInfo);
        }
        
        public bool SentHappyBirthday(out string messageInfo) {
            return base.Channel.SentHappyBirthday(out messageInfo);
        }
        
        public bool SentWeatherInfoToday(out string messageInfo) {
            return base.Channel.SentWeatherInfoToday(out messageInfo);
        }
        
        public bool LoadSchedule(out TestServiceConsole.ServiceReference1.View_ScheduleDetail[] listScheduler, out string messageInfo, System.DateTime dateNow) {
            return base.Channel.LoadSchedule(out listScheduler, out messageInfo, dateNow);
        }
        
        public bool ExecuteSchedule(out string messageInfo, string functionName) {
            return base.Channel.ExecuteSchedule(out messageInfo, functionName);
        }
    }
}
